---
- name: Converge
  hosts: all
  # Login as non-privileged user, use sudo to become root.
  remote_user: ansible
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: "Build kubo 0.15"
      include_role:
        name: "ipfs"
      vars:
        ipfs_build: true
        ipfs_version: "0.15.0"
    - name: "Upgrade to kubo 0.16"
      include_role:
        name: "ipfs"
      vars:
        ipfs_build: true
        ipfs_version: "0.16.0"
