---
- name: Load ipfs role (for restart handler)
  import_role:
    name: "ipfs"
    tasks_from: "init.yml"
- name: Configuring kubo
  environment:
    IPFS_PATH: "{{ ipfs_path }}"
  become: true
  become_user: "{{ ipfs_user }}"
  block:
  - name: Get current configuration value
    command:
      argv:
        - "{{ ipfs_binary }}"
        - --enc=json
        - config
        - --
        - "{{ item.key }}"
    loop: "{{ ipfs_config | dict2items }}"
    changed_when: false
    register: ipfs_current_config_cmd
  - name: Updating kubo configuration
    command:
      argv:
        - "{{ ipfs_binary }}"
        - config
        - --json
        - --
        - "{{ item.key }}"
        - "{{ item.value | to_json }}"
    when: item.value != (ipfs_current_config_cmd.results[index].stdout | from_json).Value
    notify: Restart ipfs
    changed_when: true
    loop: "{{ ipfs_config | dict2items }}"
    loop_control:
      index_var: index
