---
- name: Install Debian build requirements
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Install RedHat build requirements
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"
