---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Ref: https://gitlab.com/aussielunix/ansible/molecule-containers
  - name: ubuntu-20.04
    image: "registry.gitlab.com/aussielunix/ansible/molecule-containers/ubuntu:focal"
    tmpfs:
      - /run
      - /tmp
    override_command: false
    privileged: true
    pre_build_image: true
  - name: debian-11
    image: "registry.gitlab.com/aussielunix/ansible/molecule-containers/debian:bullseye"
    tmpfs:
      - /run
      - /tmp
    override_command: false
    privileged: true
    pre_build_image: true
  - name: rockylinux-9
    image: "registry.gitlab.com/aussielunix/ansible/molecule-containers/rockylinux:9"
    tmpfs:
      - /run
      - /tmp
    override_command: false
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
    verify: ../default/verify.yml
    cleanup: ../default/cleanup.yml
  env:
    ANSIBLE_PIPELINING: "True"
verifier:
  name: ansible
