---
- name: Prepare
  hosts: all
  tasks:
    - name: Install kubo
      include_role:
        name: "ipfs"
      vars:
        # Idempotence: prevent addressing side-effects.
        ipfs_profile: test
        ipfs_config:
          Addresses:
            API: /ip4/127.0.0.1/tcp/5001
            Swarm:
              - /ip4/0.0.0.0/udp/4001/quic
