galaxy_info:
  author: Mathijs de Bruin <mathijs@ipfs-search.com>
  description: Configure peering for kubo (former go-ipfs).
  company: ipfs-search.com

  issue_tracker_url: https://github.com/ipfs-search/ansible-ipfs/issues
  license: MIT

  min_ansible_version: "2.13"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Fedora
      versions:
        - "36"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - bullseye

  galaxy_tags:
    - ipfs
    - kubo

dependencies: []
