---
- name: ensure installation of IPFS build requirements
  include_role:
    name: ipfs_build_requirements
    public: yes
- name: create build user
  user:
    name: "{{ ipfs_build_user }}"
    comment: "go-ipfs build user"
    state: present
- name: create build path
  file:
    path: "{{ ipfs_build_path }}"
    state: directory
    mode: 0755
    owner: "{{ ipfs_build_user }}"
- name: clone go-ipfs
  git:
    dest: "{{ ipfs_build_path }}"
    repo: "{{ ipfs_repo }}"
    version: "{{ ipfs_version }}"
  register: source
  become: true
  become_user: "{{ ipfs_build_user }}"
- name: Check whether ipfs binary exists # noqa 503
  # For extra robustness, e.g. when build fails and clone doesn't update
  stat:
    path: "{{ ipfs_binary }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: ipfs_binary_stat
  when: not source.changed
- block:
  - block:
    - name: clean go-ipfs
      make:
        chdir: "{{ ipfs_build_path }}"
        target: clean
    - name: make go-ipfs
      make:
        chdir: "{{ ipfs_build_path }}"
        params: "{% if ipfs_openssl %}GOTAGS=openssl{% endif %}"
        target: build
    environment:
      PATH: "{{ ansible_local.golang.general.home }}/bin:{{ ansible_env.PATH }}"
    become: true
    become_user: "{{ ipfs_build_user }}"
  - name: Install ipfs binary
    copy:
      src: "{{ ipfs_build_path }}/cmd/ipfs/ipfs"
      dest: "{{ ipfs_binary }}"
      remote_src: True
      mode: 0755
      owner: root
    become: true
    notify: restart ipfs
  when: source.changed or not ipfs_binary_stat.stat.exists
