---
- name: create Ansible facts.d directory
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d
- name: install facts file
  template:
    src: ipfs.fact
    dest: /etc/ansible/facts.d/ipfs.fact
    mode: 0755
  register: ipfs_facts
- name: re-read facts after adding # noqa 503
  setup:
    filter: ansible_local
  when: ipfs_facts.changed
