---
- name: Create install user {{ ipfs_install_user }}
  user:
    name: "{{ ipfs_install_user }}"
    comment: "ipfs install user"
    state: present
- name: Check existence of {{ ipfs_binary }}
  # For extra robustness, e.g. when build fails and clone doesn't update
  stat:
    path: "{{ ipfs_binary }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: ipfs_binary_stat
- name: Install from build
  include_tasks: install_build.yml
  when: ipfs_build
- name: Install from dist
  include_tasks: install_dist.yml
  when: not ipfs_build
