---
- name: Check whether we can set systemd memory
  stat:
    path: /sys/fs/cgroup/memory
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: ipfs_cgroup_memory
  when: ipfs_hard_disable_swapping
- name: Configure service
  template:
    src: ipfs.service
    dest: "/etc/systemd/system/{{ ipfs_service_name }}.service"
    mode: 0644
  notify: Restart ipfs
- name: Enable service
  systemd:
    name: "{{ ipfs_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
