- name: Check whether we can set networking parameters
  stat:
    path: /proc/sys/net/core/rmem_max
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: ipfs_receive_buffer_proc
- name: Install sysctl
  when: ipfs_receive_buffer_proc.stat.exists # This does not work e.g. in Docker
  block:
  - name: Install sysctl
    package:
      name: procps
    when: ansible_facts['distribution'] == "Debian"
  - name: Increase UDP Receive Buffer Size for quic-go v0.19.x+
    sysctl:
      name: net.core.rmem_max
      value: "2500000"
      state: present
    notify: Restart ipfs
