---
- name: Cleanup
  hosts: all
  gather_facts: false
  tasks:
    - name: Stop ipfs daemon
      service:
        name: ipfs
        state: stopped
      ignore_unreachable: yes
      ignore_errors: yes
