---
- name: Cleanup
  hosts: all
  gather_facts: false
  ignore_unreachable: yes
  tasks:
    - name: Stop ipfs daemon
      service:
        name: ipfs
        state: stopped
      ignore_errors: yes # noqa ignore-errors
