---
- name: Converge
  hosts: all
  # Login as non-privileged user, use sudo to become root.
  remote_user: ansible
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: "Install kubo with defaults."
      include_role:
        name: "ipfs"
