---
- name: Verify
  hosts: all
  tasks:
  - name: check whether IPFS facts are defined
    assert:
      that:
        - "'ipfs' in ansible_local"
        - "'ID' in ansible_local['ipfs']"
        - "ansible_local['ipfs']['ID']"
