---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check if ipfs gateway is listening
    wait_for:
      port: 8080
      delay: 5
      timeout: 30
  - name: Check if ipfs API is listening
    wait_for:
      port: 5001
      timeout: 15
