---
- name: Install Debian build requirements
  apt:
    name:
      - build-essential
      - pkg-config
      - git
    state: present
- name: Install OpenSSL dev library
  apt:
    name: libssl-dev
  when: ipfs_openssl
