---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Ref: https://github.com/geerlingguy/ansible-role-apache/blob/master/molecule/default/molecule.yml
  # - name: instance
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    # command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  - name: centos-8
    image: "geerlingguy/docker-centos8-ansible:latest"
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
  - name: ubuntu-20.04
    pre_build_image: true
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
  - name: debian-11
    pre_build_image: true
    image: "geerlingguy/docker-debian11-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
provisioner:
  name: ansible
verifier:
  name: ansible
